config/routes.rb
Recuariments::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :projects do
    resources :collaborators
    resources :messages
    resources :requirements do
      collection do
        get :export_pdf
      end
    end
    
    member do
      post :update_order
    end
    resources :fields, as: "requirement_fields"
  end
  
  root 'projects#index'

  

end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  belongs_to :project
  
  has_many   :requirement_attributes, class_name:"RequirementFieldValues", dependent: :destroy
  validates_presence_of :requirement_attributes
  validates_associated  :requirement_attributes
  
  after_initialize :custom_getters_and_setters
  after_validation :append_nested_errors
  has_paper_trail
  
  def build_attributes_with_values(attr)
    attr.each do |key, value|
      self.send("#{key}=", value)
    end
  end
  
  def serializable_attributes
    hash = {}
    self.requirement_attributes.each do |r|
      hash[r.field_name] = r.value
    end#.map {|a| a.serializable_hash}
    hash
  end
  
  def associated_versions
    self.requirement_attributes.map {|a| a.versions }
  end
  
  def update_requirement_attributes(attr)
    attr.each do |key,value|
      logger.debug("#{key} = #{value}")
      self.send("#{key}=", value)
    end
    logger.debug("inspect object: #{self.inspect}")
    (self.errors.empty?) ? true : false
  end
  
  def custom_getters_and_setters
    self.project.fields.each do |method_name|
      self.class.class_eval do
        define_method method_name.field_name do
          record = self.requirement_attributes.find_by_requirement_field_id(method_name.id)
          record ? record.value : nil
        end
        
        define_method "#{method_name.field_name}=" do |arg|
          record =self.requirement_attributes.find_by(requirement_field_id: method_name.id)
          if record.blank?
            self.requirement_attributes.build(requirement_field: method_name, value: arg).save
          else
            unless record.update(value: arg)
              self.errors.add(method_name.field_name, record.errors.full_messages_for(:value).join(","))
            end
          end
        end
      end
    end
  end
  
  def append_nested_errors
    self.requirement_attributes.each do |attribute|
      unless attribute.valid?
       logger.debug attribute.errors.inspect
       self.errors.add(attribute.field_name, attribute.errors.full_messages_for(:value).join(","))
     end
    end
  end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  def index
    begin
      @project = current_user.projects.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path, alert: "Project not found."
    else
      @requirements = @project.requirements
    end
  end
  def new 
    @project = current_user.projects.find(params[:project_id])
    @requirement = @project.requirements.build
    @fields      = @project.fields
  end
  
  def create
    @project  = current_user.projects.find(params[:project_id])
    @requirement = @project.requirements.build

    @requirement.build_attributes_with_values(requirement_params)
    
    if @requirement.valid? && @requirement.save
      redirect_to project_requirements_path(@project), notice: "Requirement Successfully added to the project."
    else
      @fields = @project.fields      
      render :new
    end
  end
  
  def edit
    @project = current_user.projects.find(params[:project_id])
    @requirement = @project.requirements.find(params[:id])
    @fields      = @project.fields
  end
  
  def update
    @project = current_user.projects.find(params[:project_id])
    @requirement = @project.requirements.find(params[:id])
    
    if @requirement.update_requirement_attributes(requirement_params)
      redirect_to project_requirements_path(@project), notice: "Requirement Successfully updated."
    else
      @fields      = @project.fields
      render :edit
    end
  end
  
  def show
    @project = current_user.projects.find(params[:project_id])
    @requirement = @project.requirements.find(params[:id])
  end
  
  def destroy
    @project = current_user.projects.find(params[:project_id])
    @requirement = @project.requirements.find(params[:id])
    
    if @requirement.destroy
      redirect_to project_requirements_path(@project), notice: "Requirement Successfully removed."
    else
      redirect_to project_requirements_path(@project), alert: "Something went wrong."
    end
  end
  
  def export_pdf
    project = current_user.projects.find(params[:project_id])
    requirements = project.requirements
    if(requirements.empty?)
      redirect_to project_requirements_path(project), alert: "You don't have any requirement to export."
    else
      output = RequirementReport.new.to_pdf(requirements)
      send_data output, :filename => "#{project.title.parameterize.gsub('-','_')}_requirements_#{Time.now.to_i}", 
                        :type => "application/pdf"
    end
  end
  
  private
  
  def requirement_params
    params.require(:requirement).permit!
  end
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/views/requirements/_form.html.erb
<%= f.simple_fields_for :requirement_attributes, OpenStruct.new(@requirement.serializable_attributes) do |v| %>
	<% @fields.each do |field| %>
		<%= render "requirements/fields/#{field.field_type}", field:field, f:f, requirement: @requirement %>
	<% end %>
<% end %>

app/views/requirements/_requirement_list.html.erb
<table class="table" id="table-requirements-<%= @project.id %>">
	<thead>
		<tr>
			<% fields = project.fields.limit(3).map {|f| f.field_name }%>
			<% fields.each do |field| %>
				<th><%= field.humanize %></th>
			<% end %>
			<th>
				Options
			</th>
		</tr>
	</thead>
	<tbody>
		
		<% requirements.each do |requirement|%>
			<tr>
				<% fields.each do |field| %>
					<td><%= requirement.send(field).blank? ? "" : requirement.send(field).truncate(50)  %></td>
				<% end %>
				<td>
					<%= link_to "Show", project_requirement_path(project,requirement)  %> |
					<%= link_to "Edit", edit_project_requirement_path(project, requirement) %> | 
					<%= link_to "Remove", project_requirement_path(project, requirement), method: :delete, data: {confirm: "Are you sure?"} %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/requirements/edit.html.erb
<div class="col-md-12">
	<h2>Edit Requirement <small>for <%= @project.title %></small></h2>
	<%= simple_form_for [@project,@requirement] do |f| %>
		<%= render "form", f:f %>
		<div class="form-actions">
			<div class="col-md-6">
				<%= f.button :submit, "Update requirement", class:"btn btn-primary col-md-12" %>
			</div>
			<div class="col-md-6">
				<%= link_to "Cancel", :back, class:"btn btn-default col-md-12" %>
			</div>
		</div>
	<% end %>
</div>

app/views/requirements/index.html.erb
<div class="col-md-12">
	<h2>Requirements <small><%= link_to "New Requirement", new_project_requirement_path(@project) %></small></h2>
	<% if @requirements.empty? %>
		<p class="text-center">
			You don't have any requirement yet. <%= link_to "Create one", new_project_requirement_path(@project) %>
		</p>
	<% else %>
		<p><%= render "requirement_list", requirements:@requirements, project: @project %></p>
	<% end %>
	<%= link_to "Export all requirements to PDF", export_pdf_project_requirements_path(@project) %>
</div>

app/views/requirements/new.html.erb
<div class="col-md-12">
	<h2>New Requirement <small>for <%= @project.title %></small></h2>
	<% unless @project.fields.blank? %>
		<%= simple_form_for [@project,@requirement] do |f| %>
			<%= render "form", f:f %>
				<div class="form-group">
					<div class="col-md-6">
						<%= f.button :submit, "Create Requirement", class:"btn btn-primary col-md-12" %>
					</div>
					<div class="col-md-6">
						<%= link_to "Cancel", :back, class:"btn btn-default col-md-12" %>
					</div>
				</div>
		<% end %>
	<% else %>
	Create a field for a requirement first!. <%= link_to "Create one", new_project_requirement_field_path(@project) %>
	<% end %>
</div>

app/views/requirements/show.html.erb
<div class="col-md-12">
	<h2>Requirement Detail <small> for <%= @project.title %></small></h2>
	<% @requirement.requirement_attributes.each do |requirement_attribute| %>
		<div class="row">
			<div class="row">
				<div class="col-md-4">
					<strong><%= requirement_attribute.requirement_field.name %>:</strong>
				</div>
				<div class="col-md-8">
					<%= requirement_attribute.value %>
				</div>
			</div>
		</div>
	<% end %>
	<div class="row">
		<h2>Changes</h2>
		<% if @requirement.versions.empty? && @requirement.associated_versions.empty? %>
			<p class="text-centered">No changes in this requirement yet.</p>
		<% else %>
		<ul class="list-group">
			
			<% @requirement.requirement_attributes.each do |attribute| %>
			<li class="list-group-item">
				<h5><%= attribute.name %></h5>
					<% unless attribute.versions.blank? %>
						<% changes = attribute.versions.group_by { |attr| attr.created_at.in_time_zone.strftime("%B") } %>
						<% changes.each do |key,version|  %>
							<h6><%= key %></h6>
							<% unless version.empty? %>
								<% version.each do |change| %>
									<div class="row">
										<div class="col-md-12">
											<span class="label label-info">
												<%= change.changeset[:updated_at].last.day %> at <%= change.changeset[:updated_at].last.in_time_zone.strftime("%I:%M%p") %>
											</span><span class="label label-default"><%= change.whodunnit %></span>
										</div>
									</div>
									<div class="row">
										<div class="col-md-12">										
											<%= raw Diff.differ(change.changeset[:value]) %>									
										</div>
									</div>
								<% end %>
							<% end %>
						<% end %>
					<% else %>
						<p class="text-centered">No changes in this attribute yet.</p>
					<% end %>
				</li>
			<% end %>
			</ul>
		<% end %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= link_to "Go Back", project_path(@project), class: "btn btn-primary pull-right" %>
	</div>
</div>