config/routes.rb
Recuariments::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :projects do
    resources :collaborators
    resources :messages
    resources :requirements do
      collection do
        get :export_pdf
      end
    end
    
    member do
      post :update_order
    end
    resources :fields, as: "requirement_fields"
  end
  
  root 'projects#index'

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  
  has_many :memberships, inverse_of: :project, dependent: :destroy
  has_many :users, through: :memberships
  has_many :messages, dependent: :destroy
  
  # belongs_to :owner, class_name: "User"

  has_many   :requirements, dependent: :destroy
  has_many   :fields, class_name: "RequirementField", dependent: :destroy
    
  #accepts_nested_attributes_for :fields, allow_destroy: true
  validates_presence_of   :title
  has_paper_trail
  
  after_create :make_owner

  def make_owner
  	self.memberships.last.update_attribute(:owner, true)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def index
    @projects = current_user.projects
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = current_user.projects.build(project_params)
    if @project.valid? && @project.save 
      redirect_to projects_path, notice: "Project Created successfully."
    else
      render :new
    end
  end
  
  def show
    begin
      @project     = current_user.projects.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path, alert: "Project not found."
    else
      @requirements = @project.requirements
      @fields       = @project.fields      
      @collaborators = @project.memberships
      @message      = Message.new #@project.messages.build
      @messages     = @project.messages
    end

  end
  
  def edit
    begin
      @project = current_user.projects.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path, aler: "Project not found."
    end
  end
  
  
  def update
    begin
      @project = current_user.projects.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path, aler: "Project not found."
    else
      if @project.update_attributes(project_params)
       redirect_to projects_path, notice: "Project was successfully updated."
      else
        render :edit
      end
    end
  end
  
  def destroy
    begin
      @project = current_user.projects.find(params[:id])      
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path, aler: "Project not found."
    else
      begin
        current_user_is_owner = current_user.memberships.find_by_project_id(@project)
      rescue ActiveRecord::RecordNotFound
        redirect_to projects_path, alert: "Something went wrong."
      else
        if current_user_is_owner.owner
          if @project.destroy
            redirect_to projects_path, notice: "Project #{@project.title} was successfully removed."
          else
            redirect_to projects_path, alert: "Something went wrong."
          end
        else
          redirect_to projects_path, alert: "You can't do that!."
        end
      end
    end
  end
  
  def update_order
    begin
      project = current_user.projects.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to project_requirement_fields_path, alert: "Project not found."
    else
      begin
        field_to_move  = project.fields.find_by_field_name(params[:field])
        old_position_field  = project.fields.find_by_order(params[:order])
      rescue ActiveRecord::RecordNotFound
        redirect_to project_requirement_fields_path, alert: "Something went wrong."
      else
        old_position_field.order = field_to_move.order
        field_to_move.order      = params[:order]
        result = {}
        if old_position_field.valid? && field_to_move.valid? && old_position_field.save && field_to_move.save
          result = {success: true, message: "Order of attributes successfully updated!."}
        else
          result = {success: false, message: "Something went wrong."}
        end
        respond_to do |format|
          format.json { render json: result}
        end
      end
    end
  end
  
  private
  
  def project_params
    params.require(:project).permit(:title, fields_attributes: [:id, :_destroy, :name, :field_type, :required])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_field_fields.html.erb
<fieldset>
	<%= link_to '#', input_html:{class: "remove_fields"}  do %>
		<i class="icon-remove-sign"></i>
	<% end %>
	<%= f.label "Type" %>
	<%= f.input_field :field_type, as: :select, collection: RequirementField::SUPPORTED_FIELD_TYPE %>
	<%= f.label "Name"%>
	<%= f.input_field :name %>
	<%= f.input_field :required, label: false %> Required
</fieldset>

app/views/projects/_form.html.erb
<div class="row col-md-12">
	<h1>Project</h1>		
</div>
<div class="row col-md-12">
	<label>
		Project Name
	</label>
	<%= f.input_field :title, as: :string, class:" col-md-12" %>
</div>

app/views/projects/edit.html.erb
<%= simple_form_for @project, html:{class:"form-inline"} do |f| %>
	<%= render "form", f:f %>
	<%= f.button :submit, "Update Project", class:"btn btn-primary" %>
<% end %>

app/views/projects/index.html.erb
<div class="row">
	<% if @projects.empty? %>
		<p class="text-center">
			You don't have any project yet. <%= link_to "Create one", new_project_path %>
		</p>
	<% else %>
	<div class="page-header">
	  <h1>Project List <small><%= link_to "New Project", new_project_path %></small></h1>
	</div>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>
					Project Name
				</th>
				<th>
					Options
				</th>
			</tr>
		</thead>
		<tbody>
			<% @projects.each do |p| %>
				<tr>
					<td>
						<%= link_to p.title, project_path(p) %>
					</td>
					<td>
						<%= link_to "Edit", edit_project_path(p) %> | <%= link_to "Delete", project_path(p), method: :delete, data: {confirm: "Are you sure?"} %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<% end %>
</div>

app/views/projects/new.html.erb
<%= simple_form_for @project, html:{class:"form-inline"} do |f| %>
	<%= render "form", f:f %>
		<div class="row col-md-12">
			<div class="col-md-6">
				<%= f.button :submit, "Create Project", class:"btn btn-primary col-md-12" %>
			</div>
			<div class="col-md-6">
				<%= link_to "Cancel", :back, class:"btn btn-default col-md-12" %>
			</div>
		</div>
<% end %>

app/views/projects/show.html.erb
<div class="col-md-12">
	<div class="row">
		<h2><%= @project.title %></h2>
		<p class="lead">
			Welcome to the dashboard of your project. Here you can manage the recuariments, collaborators and more!.
		</p>
	</div>
</div>