config/routes.rb
Recuariments::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :projects do
    resources :collaborators
    resources :messages
    resources :requirements do
      collection do
        get :export_pdf
      end
    end
    
    member do
      post :update_order
    end
    resources :fields, as: "requirement_fields"
  end
  
  root 'projects#index'

  

end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  def index
    begin
      @project = current_user.projects.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path, alert: "Project not found."
    else
      @fields = @project.fields
    end   
  end
  
  def new
    @project = current_user.projects.find(params[:project_id])
    @requirement_attribute = @project.fields.build
  end
  
  def create
    @project = current_user.projects.find(params[:project_id])
    @requirement_attribute   = @project.fields.build(fields_params)
    
    if @requirement_attribute.valid? && @requirement_attribute.save
      redirect_to project_requirement_fields_path(@project), notice: "Successfully added new field."
    else
      render :new
    end
  end
  
  def edit
    @project = current_user.projects.find(params[:project_id])
    @requirement_attribute   = @project.fields.find(params[:id])
  end
  
  def update
    @project = current_user.projects.find(params[:project_id])
    @requirement_attribute   = @project.fields.find(params[:id])
    
    @requirement_attribute.update(fields_params)
    
    if @requirement_attribute.valid? && @requirement_attribute.save
      redirect_to project_requirement_fields_path(@project), notice: "Successfully edited!."
    else
      render :edit
    end
    
  end
  
  def destroy
    @project = current_user.projects.find(params[:project_id])
    @field = @project.fields.find(params[:id])
    
    if @field.destroy && RequirementFieldValues.destroy(RequirementFieldValues.where(requirement_field_id: @field.id).ids)
      redirect_to project_requirement_fields_path(@project), notice: "Successfully remove field."
    else
      redirect_to project_requirement_fields_path(@project), alert: "Something went wrong."
    end
  end
  
  private
  
  def fields_params
    params.require(:requirement_field).permit(:field_type, :name, :required, :unique)
  end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<div class="row col-md-12">
	<label>
		Type
	</label>
	<%= f.input_field :field_type, as: :select, collection: RequirementField::SUPPORTED_FIELD_TYPE, class:"col-md-12" %>
</div>

<div class="row col-md-12">
	<label>
		Name
	</label>
	<%= f.input_field :name, as: :string, class:"col-md-12" %>
</div>
<div class="row col-md-12">
	<%= f.input_field :required, label:false, inline_label: "Required"%>
</div>
<div class="row col-md-12">
	<%= f.input_field :unique, label: false, inline_label: "Unique"%>
</div>

app/views/fields/_requirement_fields_list.html.erb
<table class="table table-bordered" id="table-requirements-fields-<%= @project.id %>">
	<thead>
		<tr>
			<th>
				Order
			</th>
			<th>
				Field Name
			</th>
			<th>
				Field Type
			</th>
			<th>
				is Required?
			</th>
			<th>
				must be Unique?
			</th>
			<th>
				Options
			</th>
		</tr>
	</thead>
	<tbody>
		<% fields.each do |field| %>
			<tr id="<%= field.field_name %>">
				<td id="order">
					<%= field.order  %>
				</td>
				<td><%= field.name %></td>
				<td><%= field.field_type %></td>
				<td><%= field.required ? "YES" : "NO" %></td>
				<td><%= field.unique ? "YES"   : "NO" %></td>
				<td><%= link_to "Edit", edit_project_requirement_field_path(@project, field) %> | <%= link_to "Delete", project_requirement_field_path(@project,field),  method: :delete,data: {confirm: "Are you sure?"} %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/fields/edit.html.erb
<h2>Edit Field <small>for <%= @project.title %></small></h2>
<%= simple_form_for [@project,@requirement_attribute], html:{class:"form-inline"} do |f| %>
	<%= render "form", f:f %>
	<div class="row col-md-12">
		<div class="col-md-6">
			<%= f.button :submit, "Create Field", class:"btn btn-primary col-md-12" %>
		</div>
		<div class="col-md-6">
			<%= link_to "Cancel", :back, class:"btn btn-default col-md-12" %>
		</div>
	</div>
<% end %>

app/views/fields/index.html.erb
<div class="col-md-12">
	<h2>Attributes <small><%= link_to "New Attribute", new_project_requirement_field_path(@project) %></small></h2>
	<% if @fields.empty? %>
			<p class="text-center">
				You don't have any requirement attribute yet. <%= link_to "Create one", new_project_requirement_field_path(@project) %>
			</p>
	<% else %>
		<p><%= render "requirement_fields_list", fields: @fields %></p>
	<% end %>
</div>

app/views/fields/new.html.erb
<h2>New Field <small>for <%= @project.title %></small></h2>
<%= simple_form_for [@project,@requirement_attribute], html:{class:"form-inline"} do |f| %>
	<%= render "form", f:f %>
	<div class="row col-md-12">
		<div class="col-md-6">
			<%= f.button :submit, "Create Field", class:"btn btn-primary col-md-12" %>
		</div>
		<div class="col-md-6">
			<%= link_to "Cancel", :back, class:"btn btn-default col-md-12" %>
		</div>
	</div>
<% end %>