config/routes.rb
Recuariments::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :projects do
    resources :collaborators
    resources :messages
    resources :requirements do
      collection do
        get :export_pdf
      end
    end
    
    member do
      post :update_order
    end
    resources :fields, as: "requirement_fields"
  end
  
  root 'projects#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Recuariments</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">





    <!-- For sample logo only-->
    <!--Remove if you no longer need this font-->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Aguafina+Script">
    <!--For sample logo only-->
    <!-- <link rel="stylesheet" href="lib/font-awesome/css/font-awesome.css"> -->

	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
	  <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
  <body class=""> 
  <!--<![endif]-->
    
    <% if user_signed_in? %>
    <div class="navbar">
        <div class="navbar-inner">
                <ul class="nav pull-right">
                    <li id="fat-menu" class="dropdown">
                        <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-user"></i> <%= current_user.email %>
                            <i class="icon-caret-down"></i>
                        </a>

                        <ul class="dropdown-menu">
                            <li class="divider"></li>
                            <li class="divider visible-phone"></li>
                            <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
                        </ul>
                    </li>
                    
                </ul>
                <a class="brand" href="index.html">Recuariments.</a>
        </div>
    </div>
		<% end %>

    
    <div class="container">
			<%= notice_message %>
			<%= yield %>
		</div>

                
      <footer>
          <hr>
          <p class="pull-right">Design by <a href="http://www.portnine.com" target="_blank">Portnine</a></p>
          <p>&copy; 2013 <a href="#">Your Company</a></p>
      </footer>

  </body>
</html>

app/views/layouts/application_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Recuariments</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">





    <!-- For sample logo only-->
    <!--Remove if you no longer need this font-->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Aguafina+Script">
    <!--For sample logo only-->
    <!-- <link rel="stylesheet" href="lib/font-awesome/css/font-awesome.css"> -->

	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
	  <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
  <body> 
  <!--<![endif]-->
    
		<div class="container">
		  <% if user_signed_in? %>
				<div class="row">
					<nav class="navbar navbar-inverse" role="navigation">
					  <!-- Brand and toggle get grouped for better mobile display -->
					  <div class="navbar-header">
					    <a class="navbar-brand" href="#">Recuariments</a>
					  </div>
					  <!-- Collect the nav links, forms, and other content for toggling -->
					  <div class="collapse navbar-collapse navbar-ex1-collapse">
					    <ul class="nav navbar-nav navbar-right">
					      <li class="dropdown">
					        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="glyphicon glyphicon-user"></i> <%= current_user.email %> <b class="caret"></b></a>
					        <ul class="dropdown-menu">
										<li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
					        </ul>
					      </li>
					    </ul>
					  </div><!-- /.navbar-collapse -->
					</nav>
				</div>
			<% end %>
		  <div class="row">
		    <div class="col-md-12">
					<%= notice_message %>
					<%= yield %>
		    </div>
		  </div>
      <footer>
          <hr>
          <p>&copy; 2013 <a href="#">Alberto Lagos T.</a></p>
      </footer>   
		</div>
  </body>
</html>

app/views/layouts/default_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Recuariments</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">





    <!-- For sample logo only-->
    <!--Remove if you no longer need this font-->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Aguafina+Script">
    <!--For sample logo only-->






	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
    
    <link rel="stylesheet" href="lib/font-awesome/css/font-awesome.css">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
  <body class=""> 
  <!--<![endif]-->
    
    
	<div class="container">
		<%= notice_message %>
		<%= yield %>
	</div>   
  </body>
</html>

app/views/layouts/layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Recuariments</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">





    <!-- For sample logo only-->
    <!--Remove if you no longer need this font-->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Aguafina+Script">
    <!--For sample logo only-->






	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
    
    <link rel="stylesheet" href="lib/font-awesome/css/font-awesome.css">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
  <body class=""> 
  <!--<![endif]-->
    
    
	<div class="row-fluid login">
    <div class="dialog">
        <p class="brand">Recuariments.</p>
        <%= yield %>
    </div>
</div>
    <script type="text/javascript">
        $("[rel=tooltip]").tooltip();
        $(function() {
            $('.demo-cancel-click').click(function(){return false;});
        });
    </script>
    
  </body>
</html>

app/views/layouts/project_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Recuariments</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">





    <!-- For sample logo only-->
    <!--Remove if you no longer need this font-->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Aguafina+Script">
    <!--For sample logo only-->
    <!-- <link rel="stylesheet" href="lib/font-awesome/css/font-awesome.css"> -->

	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
	  <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
  <body> 
  <!--<![endif]-->
    
	<div class="container">
	  <% if user_signed_in? %>
			<div class="row">
				<nav class="navbar navbar-inverse" role="navigation">
				  <!-- Brand and toggle get grouped for better mobile display -->
				  <div class="navbar-header">
				    <a class="navbar-brand" href="#">Recuariments</a>
				  </div>
				  <!-- Collect the nav links, forms, and other content for toggling -->
				  <div class="collapse navbar-collapse navbar-ex1-collapse">
				    <ul class="nav navbar-nav navbar-right">
				      <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="glyphicon glyphicon-user"></i> <%= current_user.email %> <b class="caret"></b></a>
				        <ul class="dropdown-menu">
									<li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
				        </ul>
				      </li>
				    </ul>
				  </div><!-- /.navbar-collapse -->
				</nav>
			</div>
		<% end %>
	  <div class="row">
			<div class="col-md-2 well">
					<ul id="dashboard-menu" class="nav nav-list">
						<li class="<%= is_active?("projects") %>">
							<%= link_to project_path(@project) do %>
								<i class="glyphicon glyphicon-home"></i> <span>Dashboard</span>
							<% end %>
						</li>
						<li class="<%= is_active?("requirements")%>">
							<%= link_to project_requirements_path(@project) do %>
								<i class="glyphicon glyphicon-file"></i><span>Requirements</span>
							<% end %>
						</li>
						<li class="<%= is_active?("fields") %>">
							<%= link_to project_requirement_fields_path(@project) do %>
								<i class="glyphicon glyphicon-tasks"></i> <span>Attributes</span>
							<% end %>
						</li>
						<li class="<%= is_active?("collaborators") %>">
							<%= link_to project_collaborators_path(@project) do %>
								<i class="glyphicon glyphicon-user"></i> <span>Collaborators</span>
							<% end %>
						</li>
						<li>
							<%= link_to project_messages_path(@project) do %>
								<i class="glyphicon glyphicon-align-justify"><span>Messages</span></i>
							<% end %>
						</li>
						<li>
							<%= link_to projects_path do %>
								<i class="glyphicon glyphicon-circle-arrow-left"></i><span>Project List</span>
							<% end %>
						</li>
					</ul>
			</div>
	    <div class="col-md-10">
				<%= notice_message %>
				<%= yield %>
	    </div>
	  </div>
	  <footer>
	  	<hr>
	  	<p>&copy; 2013 <a href="#">Alberto Lagos T.</a></p>
	  </footer>         
	</div>
 </body>
</html>